using System.Text.Json;
using System.Text.Json.Serialization;

namespace PoEformance.Game.World;

/// <summary>
/// Which terrain graphs (<c>.dgr</c>) an area is generated from - WorldAreas' own Topologies column - and so which folder of the install its terrain lives in.
/// </summary>
/// <remarks>
/// WHAT IT IS FOR. A boss's arena is a tile of the area the game lists him as the boss of, and
/// the area's tiles are named by the tileset its master (<c>.tsi</c>) points at. The master sits in
/// the folder above the graph's <c>Graphs/</c> - the road RePoE walks from WorldAreas through
/// Topologies to the master, and the one AreaRoomSet walks from a folder to its masters - so the
/// graph's folder is the whole of what the Monster Book needs to offer the arena as a stage without
/// the area being loaded. See AreaArenas.
///
/// A FILE AND NOT A READ OF THE CLIENT, for now: WorldAreaCatalogue reads the rows the game holds
/// and could read this column too, but the graphs do not move between the export and the client the
/// way a boss can, and data/area-graphs.json is generated by scripts/area-graphs.py from the same
/// export data/area-bosses.json is. Stale with a patch, which offers the wrong tiles and breaks nothing.
/// </remarks>
public sealed class AreaGraphs
{
    /// <summary>The folder a map's graphs sit in, under the folder that holds its masters.</summary>
    private const string GraphsFolder = "/Graphs/";

    private readonly IReadOnlyDictionary<string, IReadOnlyList<string>> _areas;

    private AreaGraphs(IReadOnlyDictionary<string, IReadOnlyList<string>> areas, string source)
    {
        _areas = areas;
        Source = source;
    }

    /// <summary>Nothing known, which is what a missing file leaves.</summary>
    public static AreaGraphs Empty => new(new Dictionary<string, IReadOnlyList<string>>(StringComparer.OrdinalIgnoreCase), string.Empty);

    /// <summary>Where the file says it came from, for the report. Empty when nothing loaded.</summary>
    public string Source { get; }

    /// <summary>How many areas the file named a graph for.</summary>
    public int Count => _areas.Count;

    /// <summary>Loads the file, or returns <see cref="Empty"/> when it is missing or unreadable. Never throws.</summary>
    public static AreaGraphs Load(string? path)
    {
        if (string.IsNullOrWhiteSpace(path) || !File.Exists(path))
        {
            return Empty;
        }

        try
        {
            using FileStream stream = File.OpenRead(path);
            AreaGraphFile? file = JsonSerializer.Deserialize(stream, AreaGraphJson.Default.AreaGraphFile);
            if (file?.Areas is null)
            {
                return Empty;
            }

            var built = new Dictionary<string, IReadOnlyList<string>>(file.Areas.Count, StringComparer.OrdinalIgnoreCase);
            foreach ((string area, string[] graphs) in file.Areas)
            {
                if (graphs is { Length: > 0 })
                {
                    built[area] = graphs;
                }
            }

            return new AreaGraphs(built, file.Source ?? string.Empty);
        }
        catch (Exception exception) when (exception is IOException or JsonException or UnauthorizedAccessException)
        {
            return Empty;
        }
    }

    /// <summary>The graphs of an area, in the table's order, or nothing.</summary>
    public IReadOnlyList<string> Of(string? areaId)
        => areaId is { Length: > 0 } && _areas.TryGetValue(areaId, out IReadOnlyList<string>? found) ? found : [];

    /// <summary>
    /// The folders an area's terrain lives in, with their trailing slash, distinct: above each graph's <c>Graphs/</c>, or the graph's own where it has none.
    /// </summary>
    /// <remarks>
    /// THREE GRAPHS OF 432 AREAS' SIT IN NO <c>Graphs/</c> FOLDER - the hideout arenas, whose
    /// <c>hideout.dgr</c> lies beside its master - so a graph without the segment names its own folder.
    /// </remarks>
    public IReadOnlyList<string> FoldersOf(string? areaId)
    {
        IReadOnlyList<string> graphs = Of(areaId);
        if (graphs.Count == 0)
        {
            return [];
        }

        var folders = new List<string>(graphs.Count);
        foreach (string graph in graphs)
        {
            string folder = FolderOf(graph);
            if (folder.Length > 0 && !folders.Contains(folder, StringComparer.OrdinalIgnoreCase))
            {
                folders.Add(folder);
            }
        }

        return folders;
    }

    /// <summary>The folder above a graph's <c>Graphs/</c>, or the graph's own folder, with its trailing slash.</summary>
    public static string FolderOf(string graph)
    {
        ArgumentNullException.ThrowIfNull(graph);
        string path = graph.Replace('\\', '/').Trim();
        int graphs = path.LastIndexOf(GraphsFolder, StringComparison.OrdinalIgnoreCase);
        if (graphs >= 0)
        {
            return path[..(graphs + 1)];
        }

        int slash = path.LastIndexOf('/');
        return slash < 0 ? string.Empty : path[..(slash + 1)];
    }
}

/// <summary>The file's shape. See scripts/area-graphs.py, which writes it.</summary>
internal sealed class AreaGraphFile
{
    [JsonPropertyName("source")]
    public string? Source { get; init; }

    [JsonPropertyName("areas")]
    public Dictionary<string, string[]>? Areas { get; init; }
}

/// <summary>Source-generated so the file still loads under Native AOT.</summary>
[JsonSerializable(typeof(AreaGraphFile))]
internal sealed partial class AreaGraphJson : JsonSerializerContext;
