namespace PoEformance.Game.World;

/// <summary>
/// The game's own random number generator, reproduced exactly.
/// </summary>
/// <remarks>
/// TinyMT32, as the PoE2 binary implements it - which is NOT as reference TinyMT does. The state
/// transition uses <c>x &gt;&gt; 1</c> and <c>s3 &lt;&lt; 1</c> where the published algorithm uses
/// <c>x &lt;&lt; 1</c> and <c>y &gt;&gt; 1</c>, and the seeding starts from constants that already
/// have the pre-step applied. Writing the textbook version here would produce a perfectly good
/// generator that agrees with the game on nothing.
///
/// WHY A TOOL CONTAINS A GAME'S RNG AT ALL: the ritual line's rewards are rolled CLIENT-SIDE and
/// deterministically, from the line's id, how many maps are committed and which candidate a node
/// is. Reproducing the roll is what lets a reward be shown BEFORE the map is picked, which is the
/// whole of the ritual feature.
///
/// Reverse-engineered by yokkenUA for GameHelper2's Atlas plugin, from Ghidra analysis of
/// TinyMT_seedAndJump (14156b620), next32 (1404e16d0) and randBelow (1404e17a0). Ported here and
/// checked against vectors generated by that implementation itself rather than against a second
/// reading of it - see the tests.
///
/// A STRUCT, and mutable, because the generator IS its state: every draw advances it, and the
/// caller passing one around by value is what keeps two rolls from sharing a stream by accident.
/// </remarks>
public struct RitualRandom
{
    private const uint Mat1 = 0x8F7011EEu;
    private const uint Mat2 = 0xFC78FF1Fu;
    private const uint Tmat = 0x3793FDFFu;

    private uint _s0;
    private uint _s1;
    private uint _s2;
    private uint _s3;

    /// <summary>
    /// Seeds from four words and performs the jump, exactly as the game does.
    /// </summary>
    /// <remarks>
    /// Four words because that is the game's seed: the line's id, the committed count, which
    /// candidate the node is, and a fourth that means different things in different rolls - the
    /// mod's index for a pick, a fixed salt for the second-mod coin flip.
    ///
    /// The initial state is the published constants with the pre-step already applied, then four
    /// absorb rounds, three mixing rounds, four finalisation rounds and eight state advances.
    /// None of that is negotiable: every count is the binary's.
    /// </remarks>
    public static RitualRandom Seed(uint w0, uint w1, uint w2, uint w3)
    {
        Span<uint> s = [0x40336052u, 0xCFA3723Cu, 0x3CAC5F71u, 0x3793FDFFu];
        Span<uint> w = [w0, w1, w2, w3];
        int r = 1;

        for (int i = 0; i < 4; i++)
        {
            int a = (r + 1) & 3, b = r & 3, c = (r + 3) & 3;
            uint x = s[a] ^ s[c] ^ s[b];
            uint h = ((x >> 27) ^ x) * 0x19660Du;
            s[a] += h;
            uint h2 = h + w[i] + (uint)r;
            s[(r + 2) & 3] += h2;
            s[b] = h2;
            r = a;
        }

        for (int k = 0; k < 3; k++)
        {
            int a = (r + 1) & 3, b = r & 3, c = (r + 3) & 3;
            uint x = s[a] ^ s[c] ^ s[b];
            uint h = ((x >> 27) ^ x) * 0x19660Du;
            uint h2 = h + (uint)r;
            s[a] += h;
            s[(r + 2) & 3] += h2;
            s[b] = h2;
            r = a;
        }

        for (int k = 0; k < 4; k++)
        {
            int a = (r + 1) & 3, b = r & 3, c = (r + 3) & 3;
            uint x = s[c] + s[a] + s[b];
            x = ((x >> 27) ^ x) * 0x5D588B65u;
            uint y = x - (uint)r;
            s[a] ^= x;
            s[(r + 2) & 3] ^= y;
            s[b] = y;
            r = a;
        }

        var seeded = new RitualRandom { _s0 = s[0], _s1 = s[1], _s2 = s[2], _s3 = s[3] };
        for (int k = 0; k < 8; k++)
        {
            seeded.Advance();
        }

        return seeded;
    }

    /// <summary>One tempered draw, advancing the state.</summary>
    public uint Next()
    {
        uint oldS1 = _s1, oldS2 = _s2;
        uint x = (_s0 & 0x7FFFFFFFu) ^ _s1 ^ _s2;
        uint t = _s3 ^ (_s3 << 1);
        x = (x >> 1) ^ x ^ t;
        uint mag = (x & 1) != 0 ? 0xFFFFFFFFu : 0u;
        uint newS2 = (mag & Mat2) ^ (x << 10) ^ t;

        _s0 = oldS1;
        _s1 = (mag & Mat1) ^ oldS2;
        _s2 = newS2;
        _s3 = x;

        uint v = (newS2 >> 8) + oldS1;
        uint magt = (v & 1) != 0 ? 0xFFFFFFFFu : 0u;
        return (magt & Tmat) ^ v ^ x;
    }

    /// <summary>
    /// A number below <paramref name="bound"/>, with the game's own rejection rule.
    /// </summary>
    /// <remarks>
    /// The rejection matters even though it fires rarely: it is what makes the sequence agree
    /// with the game's on every seed rather than on most of them, and a prediction that is
    /// occasionally wrong is worse than none - it would be believed.
    /// </remarks>
    public uint Below(uint bound)
    {
        if (bound <= 1)
        {
            return 0;
        }

        const uint whole = 0xFFFFFFFFu;
        while (true)
        {
            uint drawn = Next();
            if (whole / bound <= drawn / bound && whole % bound != bound - 1)
            {
                continue;
            }

            return drawn % bound;
        }
    }

    /// <summary>Advances the state without producing a number. The seeding's jump.</summary>
    private void Advance()
    {
        uint x = (_s0 & 0x7FFFFFFFu) ^ _s1 ^ _s2;
        uint t = _s3 ^ (_s3 << 1);
        x = (x >> 1) ^ x ^ t;
        uint mag = (x & 1) != 0 ? 0xFFFFFFFFu : 0u;
        uint oldS1 = _s1, oldS2 = _s2;

        _s0 = oldS1;
        _s1 = (mag & Mat1) ^ oldS2;
        _s2 = (mag & Mat2) ^ (x << 10) ^ t;
        _s3 = x;
    }
}
