#!/usr/bin/env python3
"""Turn WorldAreas' Bosses column into data/area-bosses.json.

WHAT THIS ANSWERS, AND WHY IT WAS WORTH LOOKING FOR. "Which boss stands in this
map" was treated here as something only a person could know, because the monster
is not in the entity list until the area around it loads and nothing in
MinimapIcons joins the two (see BossIcons). That is true of the ICON and false of
the BOSS: WorldAreas.dat carries a Bosses column, a list of MonsterVarieties
references, and it names the boss of 125 of the atlas's 173 maps.

Measured against data/atlas-maps.json on the 4.5.5.2 export:

    173 atlas maps, 125 with a boss listed, 104 distinct bosses
    34 of those bosses stand in more than one map - Saphira is the boss of
    Grimhaven AND Epitaph, which is the case that is easy to miss by hand
    the 48 with no boss are exactly the hideouts, hubs, Expedition logbooks,
    merchant maps and Delirium towns

Over every area rather than only the atlas: 206 areas, 182 distinct bosses, of
which 181 are named by data/monster-varieties.json. The one that is not is
Metadata/Monsters/NPC/DogTrader_, which is an NPC - so the column is "mostly the
boss" rather than "definitely the boss", and an entry can be overridden by hand
in data/boss-icons.json.

THE PATH IS KEPT, NOT A NAME OR A FAMILY. The monster's metadata path is the
game's own identity for it; the icon family (WifeMonsterMap) and the label
("Saphira, The Dread Consort") are both derived from it downstream, by the same
rules the model pane's export uses for its file names. Deriving here would bake
one of those rules into a data file.

Run it against a checkout of an export repository:

    python3 scripts/area-bosses.py path/to/poe2/data/world_areas.json \\
        data/area-bosses.json --version 4.5.5.2

THIS FILE IS A STARTING POINT, NOT THE TRUTH. It is a third-party export of a
table the client itself holds, so it goes stale with a patch; AreaBosses takes
the game's own reading over it wherever one is available, the same arrangement
AtlasMapNames.LearnUnique has with its file.
"""

from __future__ import annotations

import argparse
import json
import sys


def bosses_of(areas: dict) -> dict[str, list[str]]:
    """Every area that names a boss, in id order."""
    found = {}
    for area_id, area in sorted(areas.items()):
        listed = area.get("bosses") or []
        # Order is the table's own. Where a map lists several - a boss with two
        # forms, the two Reactor Guardians of a Precursor tower - the first is
        # tried first and the rest stay available.
        kept = [path for path in listed if isinstance(path, str) and path.strip()]
        if kept:
            found[area_id] = kept

    return found


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("world_areas", help="world_areas.json from an export repository")
    parser.add_argument("out", help="where to write data/area-bosses.json")
    parser.add_argument("--version", default="", help="the export's client version, for the record")
    args = parser.parse_args()

    with open(args.world_areas, encoding="utf-8") as handle:
        areas = json.load(handle)

    found = bosses_of(areas)
    if not found:
        print("no area in that file names a boss - is it a world_areas export?", file=sys.stderr)
        return 1

    document = {
        "comment": [
            "Which boss the game says stands in an area - WorldAreas.dat's Bosses column.",
            "",
            "GENERATED by scripts/area-bosses.py from a third-party export of the game's own",
            "tables; see that script for what it measured and why the monster's PATH is what is",
            "kept here. Do not edit by hand: a correction belongs in data/boss-icons.json, which",
            "is consulted first and survives a regeneration of this file.",
            "",
            "WHAT IT IS FOR. A boss arena is found in the shape of the ground before anything is",
            "standing in it, and this says whose arena it is - so the marker carries the boss's",
            "name from the moment the area loads, and the icon made from that boss's model is",
            "matched to every map it is the boss of rather than to the one somebody was in.",
            "",
            "SEVERAL PATHS MEAN SEVERAL MONSTERS, in the table's own order: a boss with two forms",
            "(the Baron, human and wolf) or two guardians in one map (the Precursor towers). The",
            "first is used where one has to be chosen.",
            "",
            "IT GOES STALE WITH A PATCH, and is meant to: the client holds this table, so the",
            "tool reads it from the game where it can and falls back to this. See AreaBosses.",
        ],
        "source": f"WorldAreas.dat via a poe2 data export{f', client {args.version}' if args.version else ''}",
        "areas": found,
    }

    with open(args.out, "w", encoding="utf-8") as handle:
        json.dump(document, handle, indent=2, ensure_ascii=False)
        handle.write("\n")

    paths = {path for listed in found.values() for path in listed}
    print(f"{len(found)} areas, {len(paths)} distinct bosses -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
