#!/usr/bin/env python3
"""Turn WorldAreas' Topologies column into data/area-graphs.json: each area's terrain graphs.

WHAT THIS ANSWERS. Which folder of the install an area's terrain is built from - and so which
master (.tsi), which tileset and which tiles - is written in WorldAreas.dat's Topologies column,
a list of Topologies rows each naming a .dgr graph: Metadata/Terrain/Maps/VaalFactory/Graphs/
VaalFactory_01.dgr for The Assembly. The folder above Graphs/ holds the area's masters, and
AreaRoomSet already walks from a folder to its masters and their room set; AreaArenas walks the
same folder to its tileset's tiles and picks out the ones named for a boss arena, which is what
the Monster Book offers as a stage for the boss of that area without the area having to be
loaded.

Measured on the RePoE fork's export: 442 areas, 432 with a graph, 1 to 6 graphs each.

Run it against an export - RePoE's poe2/world_areas.json, as area-bosses.py is:

    python3 scripts/area-graphs.py path/to/world_areas.json data/area-graphs.json --source "RePoE poe2 export, 2026-10-10"

THIS FILE IS A STARTING POINT, NOT THE TRUTH: a third-party export of a table the client
holds, stale with a patch. A map whose graphs moved offers the wrong tiles, not a crash.
"""

from __future__ import annotations

import argparse
import json


def graphs_of(areas: dict) -> dict[str, list[str]]:
    """Every area that names a graph, in id order, each graph once and with forward slashes."""
    found = {}
    for area_id, area in sorted(areas.items()):
        kept = []
        for topology in area.get("topologies") or []:
            file = topology.get("file") if isinstance(topology, dict) else None
            if isinstance(file, str) and file.strip():
                path = file.strip().replace("\\", "/")
                if path not in kept:
                    kept.append(path)
        if kept:
            found[area_id] = kept
    return found


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("world_areas", help="world_areas.json from an export repository")
    parser.add_argument("out", help="where to write data/area-graphs.json")
    parser.add_argument("--source", default="", help="what to record as the export this came from")
    args = parser.parse_args()

    with open(args.world_areas, encoding="utf-8") as handle:
        areas = json.load(handle)
    if isinstance(areas, list):
        areas = {area["id"]: area for area in areas}

    graphs = graphs_of(areas)
    document = {
        "comment": [
            "Each area's terrain graphs (.dgr) - WorldAreas.dat's Topologies column.",
            "",
            "GENERATED by scripts/area-graphs.py from a third-party export of the game's own",
            "tables; see that script. Do not edit by hand.",
            "",
            "WHAT IT IS FOR. The folder above a graph's Graphs/ holds the area's masters (.tsi),",
            "whose tileset lists the area's tiles - among them the boss arena, which the Monster",
            "Book offers as a stage for the area's boss. See AreaArenas.",
        ],
        "source": args.source,
        "areas": graphs,
    }
    with open(args.out, "w", encoding="utf-8") as handle:
        json.dump(document, handle, indent=2, ensure_ascii=False)
        handle.write("\n")
    print(f"{len(graphs)} areas with graphs of {len(areas)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
